packages:
  all:
  # note the compiler and providers specifications
  # only suggest a priority order, they do not exclude other options
  # suggested priority for compilers.
    compiler: [ gcc@12.1.0, cce@14.0.3, aocc@3.2.0 ]
    providers:
      mpi: [ cray-mpich ]
      blas: [ openblas, amdblis ] #, cray-libsci ] # commenting out cray-libsci as bug was identified
      lapack: [ openblas, netlib-lapack, amdlibflame ] #, cray-libsci ]
      scalapack: [ netlib-scalapack, amdscalapack ] #, cray-libsci ]
      fftw-api: [ fftw, amdfftw ] #, cray-fftw ] # commenting out cray-fftw for now, similar to cray-libsci
      pkgconfig: [ pkg-config ]
    permissions:
      read: world
      # this should be user, we do not want pawsey0001 users 
      # to accidentally edit the system wide installation
      write: user
      # using default group
      # fine, considering world readable and user writable
      # could not use $PAWSEY_PROJECT, as variables are apparently not evaluated here

# don't build virtuals with an external provider
  mpi:
    buildable: false
# Left buildable, as currently built by Spack, 
# because cray-libsci and cray-fftw are not in use (see below)
#  blas:
#    buildable: false
#  lapack:
#    buildable: false
#  scalapack:
#    buildable: false
# FFTW non buildable, to avoid proliferation of variants, 
# that are ultimately a subset of the system-wide one (env_num_libs)
# Edit: FFTW buildable, otherwise in Spack 0.17.0 the concretiser crashes
#  fftw-api:
#    buildable: false
  pkgconfig:
    buildable: false
# don't build compilers neither
  cce:
    buildable: false
  gcc:
    buildable: false
  aocc:
    buildable: false
  intel:
    buildable: false
  pgi:
    buildable: false

  # GENERAL NOTES:
  # 1. for each package, only one entry must exist in this yaml
  # otherwise only the last one is considered, and the previous ones are ingored
  # 2. when externals are specified, the preferred version is respected only if it is one of the externals

  #TODO for next stack builds: consider adding more +pic as default variant

  # preferred versions and variants, dependencies
  # required by env_devel/hpctoolkit, but good to have for everything
  libunwind:
    variants: '+pic'
  mbedtls:
    variants: '+pic'
  zlib:
    version : [1.2.13]
  # preferred versions and variants, utils/python
  # Note: setting autoconf/automake/cmake as non buildable
  cmake:
    version: [3.21.4]
# Commented out - see GENERAL NOTES above
#    externals:
#  # manual addition with the latest version
#    - spec: cmake@3.21.4
#      prefix: /lus/joey/home/mdelapierre/Spack-sprints/v0.17.0_new/spack/opt/spack/cray-sles15-zen2/gcc-10.3.0/cmake-3.21.4-dgyicf6mmctyfw2fdzeja2jt5jf5gzl5
#    - spec: cmake@3.10.2
#      prefix: /usr
  ffmpeg:
    version: [4.4]
    variants: '+avresample'
  gnuplot:
    version: [5.4.2]
    variants: '+X'
  llvm:
    variants: '~omp_as_runtime ~clang ~compiler-rt ~polly ~gold'
  # preferred versions and variants, python
  python:
    version: [3.9.15]
    variants: '+optimizations +zlib'
  gdbm:
    version: [1.19]
  gettext:
    version: [0.21.1]
# Commented out - see GENERAL NOTES above
#    externals:
#    - spec: python@3.9.7+optimizations
#      prefix: /lus/joey/home/mdelapierre/Spack-sprints/v0.17.0_new/spack/opt/spack/cray-sles15-zen2/gcc-10.3.0/python-3.9.7-2nk3ozgzzug2migecarn5ez4ppjov2oe
#    - spec: python@3.8.5
#      prefix: /opt/cray/pe/python/3.8.5.1
#    - spec: python@3.6.12
#      prefix: /usr
#    - spec: python@2.7.17
#      prefix: /usr
  py-cython:
    version: [0.29.24]
  py-dask:
    version: [2021.6.2]
  py-h5py:
    version: [3.4.0]
  py-ipython:
    version: [7.28.0]
  py-matplotlib:
    version: [3.4.3]
    variants: '+movies'
  py-mpi4py:
    version: [3.1.2]
  py-numba:
    version: [0.54.0]
  py-numpy:
    version: [1.20.3]
  py-pandas:
    version: [1.3.4]
  py-pip:
    version: [22.2.2]
  py-plotly:
    version: [5.2.2]
  py-scikit-learn:
    version: [1.0.1]
  py-scipy:
    version: [1.7.1]
  py-setuptools:
    version: [57.4.0]
  # preferred versions and variants, compilers
  go:
    version: [1.16.12]
  julia:
     version: [1.6.1]
  openjdk:
    version: [17.0.0_35]
  r:
    version: [4.1.0]
# Commented out - see GENERAL NOTES above
#    externals:
#    - spec: r@4.0.5.1
#      prefix: /opt/cray/pe/R/4.0.5.1
  perl:
    version: [5.34.0]
# Commented out - see GENERAL NOTES above
#    externals:
#    - spec: perl@5.26.1~cpanm
#      prefix: /usr
  ruby:
    version: [3.0.1]
  rust:
    version: [1.52.1]
  # preferred versions and variants, num_libs
  amdblis:
    version: [3.0]
    variants: 'threads=openmp'
  amdlibflame:
    version: [3.0]
    variants: 'threads=openmp'
  amdscalapack:
    version: [3.0]
    variants: 'build_type=Release'
  aocl-sparse:
    version: [3.0]
    variants: 'build_type=Release'
  amdfftw:
    version: [3.0]
    variants: 'precision=float,double,long_double'
  amdlibm:
    version: [3.0]
  blaspp:
    version: [2021.04.01]
    variants: '~cuda build_type=Release'
  boost:
    version: [1.80.0]
    variants: '+mpi +numpy +python'
  eigen:
    version: [3.4.0]
    variants: 'build_type=Release'
  fftw:
    version: [3.3.9,2.1.5]
    variants: '+openmp precision=float,double,long_double'
  gsl:
    version: [2.6]
  hpx:
    version: [1.6.0]
    variants: '+async_mpi malloc=jemalloc max_cpu_count=128 networking=mpi cxxstd=14 build_type=Release'
  kokkos:
    version: [3.4.01]
    variants: '+hwloc +memkind +numactl +openmp +tuning cxxstd=14 build_type=Release'
  netlib-lapack:
    version: [3.9.1]
    variants: 'build_type=Release'
  openblas:
    version: [0.3.21]
    variants: 'threads=openmp'
  opencv:
     version: [4.5.2]
     variants: 'build_type=Release'
  plasma:
    version: [20.9.20]
    variants: 'build_type=Release'
  petsc:
    version: [3.15.5]
    variants: '+fftw' # commenting out trilinos as per environment note # +trilinos'
  plumed:
    version: [2.7.2]
  netlib-scalapack:
    version: [2.1.0]
  slate:
    version: [2021.05.02]
    variants: '~cuda build_type=Release'
  trilinos:
    version: [13.0.1]
    variants: '+adios2 +openmp +python build_type=Release'
# preferred versions and variants, io_libs
  hdf5:
    version: [1.12.1]
    variants: 'api=v112 +hl +fortran +szip build_type=Release'
  hdf:
    variants: '+external-xdr'
  adios2:
    version: [2.7.1]
    variants: '+python +hdf5 build_type=Release'
  netcdf-c:
    version: [4.8.1]
    variants: '+hdf4 +parallel-netcdf'
  netcdf-cxx:
    version: [4.2]
  netcdf-cxx4:
    version: [4.3.1]
  netcdf-fortran:
    version: [4.5.3]
  parallel-netcdf:
    version: [1.12.2]
  py-h5netcdf:
    version: [0.10.0]
  py-netcdf4:
    version: [1.5.3]
# for end users apps, prefer cmake variant build_type=Release
  caliper:
    variants: 'build_type=Release'
  gromacs:
    variants: 'build_type=Release'
  lammps:
    variants: 'build_type=Release'
  nektar:
    variants: 'build_type=Release'
  visit:
    variants: 'build_type=Release'

  #for astro packages prefer release
  casacore:
    variants: 'build_type=Release'
  everybeam:
    variants: 'build_type=Release'
  wsclean:
    variants: 'build_type=Release'
  idg:
    variants: 'build_type=Release'
  cghcentre:
    variants: 'build_type=Release'

  # ===========================================================================
  #                                  EXTERNALS
  # ===========================================================================



  # ---------------------------------------------------------------------------
  #                                     ROCM
  # ---------------------------------------------------------------------------
  atmi:
    externals:
    - spec: atmi@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  comgr:
    externals:
    - spec: comgr@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hip:
    externals:
    - spec: hip@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hipblas:
    externals:
    - spec: hipblas@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hipcub:
    externals:
    - spec: hipcub@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hipfft:
    externals:
    - spec: hipfft@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hipfort:
    externals:
    - spec: hipfort@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hipify-clang:
    externals:
    - spec: hipify-clang@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hip-rocclr:
    externals:
    - spec: hip-rocclr@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hipsolver:
    externals:
    - spec: hipsolver@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hipsparse:
    externals:
    - spec: hipsparse@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hsakmt-roct:
    externals:
    - spec: hsakmt-roct@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  hsa-rocr-dev:
    externals:
    - spec: hsa-rocr-dev@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  llvm-amdgpu:
    externals:
    - spec: llvm-amdgpu@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rccl:
    externals:
    - spec: rccl@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocalution:
    externals:
    - spec: rocalution@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocblas:
    externals:
    - spec: rocblas@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocfft:
    externals:
    - spec: rocfft@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-bandwidth-test:
    externals:
    - spec: rocm-bandwidth-test@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-clang-ocl:
    externals:
    - spec: rocm-clang-ocl@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-cmake:
    externals:
    - spec: rocm-cmake@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-dbgapi:
    externals:
    - spec: rocm-dbgapi@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-debug-agent:
    externals:
    - spec: rocm-debug-agent@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-device-libs:
    externals:
    - spec: rocm-device-libs@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-gdb:
    externals:
    - spec: rocm-gdb@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocminfo:
    externals:
    - spec: rocminfo@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-openmp-extras:
    externals:
    - spec: rocm-openmp-extras@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-smi:
    externals:
    - spec: rocm-smi@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-smi-lib:
    externals:
    - spec: rocm-smi-lib@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-tensile:
    externals:
    - spec: rocm-tensile@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-validation-suite:
    externals:
    - spec: rocm-validation-suite@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocprim:
    externals:
    - spec: rocprim@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocprofiler-dev:
    externals:
    - spec: rocprofiler-dev@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocrand:
    externals:
    - spec: rocrand@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocsolver:
    externals:
    - spec: rocsolver@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocsparse:
    externals:
    - spec: rocsparse@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocthrust:
    externals:
    - spec: rocthrust@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  roctracer-dev:
    externals:
    - spec: roctracer-dev@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  roctracer-dev-api:
    externals:
    - spec: roctracer-dev-api@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocwmma:
    externals:
    - spec: rocwmma@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false

# The following libraries have not been installed yet

  aomp:
    externals:
    - spec: aomp@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocm-opencl:
    externals:
    - spec: rocm-opencl@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rocmlir:
    externals:
    - spec: rocmlir@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  rccl-tests:
    externals:
    - spec: rccl-tests@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  migraphx:
    externals:
    - spec: migraphx@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  miopengemm:
    externals:
    - spec: miopengemm@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  miopen-hip:
    externals:
    - spec: miopen-hip@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  miopen-opencl:
    externals:
    - spec: miopen-opencl@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  miopen-tensile:
    externals:
    - spec: miopen-tensile@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  mivisionx:
    externals:
    - spec: lustre@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false
  mlirmiopen:
    externals:
    - spec: mlirmiopen@5.4.3
      prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev0
    buildable: false

# ----------------------------------------------------------------------------
#                                        CRAY
# ----------------------------------------------------------------------------
  lustre:
    externals:
    - spec: lustre@2.15.0.2_rc2_cray_113_g62287d0
      prefix: /usr
    buildable: false

# adding prefixes as in NERSC Perlmutter configs
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.19%gcc
      modules:
      - cray-mpich/8.1.19
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.19/ofi/gnu/9.1
    - spec: cray-mpich@8.1.19%cce
      modules:
      - cray-mpich/8.1.19
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.19/ofi/cray/10.0
    - spec: cray-mpich@8.1.19%aocc
      modules:
      - cray-mpich/8.1.19
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.19/ofi/aocc/3.0
    buildable: false
# Cray-LibSci: commenting out, as bug was identified (21 December 2021)
#  cray-libsci:
#    externals:
#    - spec: cray-libsci@22.08.1.1%gcc
#      modules:
#      - cray-libsci/22.08.1.1
#      prefix: /opt/cray/pe/libsci/22.08.1.1/gnu/9.1/x86_64
#    - spec: cray-libsci@21.08.1.2%cce
#      modules:
#      - cray-libsci/22.08.1.1
#      prefix: /opt/cray/pe/libsci/22.08.1.1/cray/9.0/x86_64
#    - spec: cray-libsci@22.08.1.1%aocc
#      modules:
#      - cray-libsci/22.08.1.1
#      prefix: /opt/cray/pe/libsci/22.08.1.1/aocc/2.0/x86_64
#    buildable: false
# Cray-FFTW: commenting out, as for Cray-Libsci
#  cray-fftw:
#    externals:
#    - spec: cray-fftw@3.3.10.1 target=zen3
#      modules:
#      - craype-x86-milan
#      - cray-fftw/3.3.10.1
#      prefix: /opt/cray/pe/fftw/3.3.10.1/x86_milan
#    - spec: cray-fftw@3.3.10.1 target=zen3
#      modules:
#      - craype-x86-milan
#      - cray-fftw/3.3.10.1
#      prefix: /opt/cray/pe/fftw/3.3.10.1/x86_milan
#    buildable: false
  # more cray
  # no longer present on setonix
  #jemalloc:
  #  externals:
  #  - spec: jemalloc@5.1.0.4
  #    modules:
  #    - cray-jemalloc/5.1.0.4
  #    prefix: /opt/cray/pe/jemalloc/5.1.0.4
  #  buildable: false
  xpmem:
    externals:
    - spec: xpmem@2.4.4
      modules:
      - xpmem/xpmem/2.4.4-2.3_9.1__gff0e1d9.shasta
      prefix: /opt/cray/xpmem/xpmem/2.4.4-2.3_9.1__gff0e1d9.shasta
    buildable: false
  libfabric:
    externals:
    - spec: libfabric@1.11.0.4.128
      modules:
      - libfabric/1.11.0.4.128
      prefix: /opt/cray/libfabric/1.11.0.4.128
    buildable: false
  # no longer on setonix
  #ucx:
  #  externals:
  #  - spec: ucx@2.7.0-1
  #    modules:
  #    - cray-ucx/2.7.0-1
  #    prefix: /opt/cray/pe/cray-ucx/2.7.0-1/ucx
  #  buildable: false
  papi:
    externals:
    - spec: papi@6.0.0.16
      modules:
      - papi/6.0.0.16
      prefix: /opt/cray/pe/papi/6.0.0.16
    buildable: false

# cray hdf5
# cray parallel-netcdf
# cray netcdf
# taken out, as cray is dropping support, and there are missing APIs any way
# available in examples/joey_sprint/configs/packages.yaml up to commit 5c797eefebf8264cba1930c64c5fba7aa0ac6edd

# python additions, based on loading cray-python and running pip list 
# we have tried to use them as externals, but Spack does not use them correctly:
# 1. if specified with ^python@3.9.7, concretisation always fail
# 2. if specified without ^python@3.9.7, would be used also with the wrong python versions
# therefore, taken out
# available in examples/joey_sprint/configs/packages.yaml up to commit bfef602ee1e7f5ae7bdb5c6b5120f116df4bea18

