upstreams:
# this is the location of the system wide installation
# it acts as an upstream installation for user-specific installations
  system_wide:
    install_tree: SOFTWARESTACK_ROOT_DIR/software
# autoload+upstream currently does not work, 
# so better not to expose upstreams modules to user installations
#    modules:
#      lmod: SOFTWARESTACK_ROOT_DIR/modules
