packages:
  all:
  # note the compiler and providers specifications
  # only suggest a priority order, they do not exclude other options
  # suggested priority for compilers.
    compiler: [gcc@10.3.0,cce,aocc]
    providers:
      mpi: [cray-mpich]
      blas: [cray-libsci]
      lapack: [cray-libsci]
      scalapack: [cray-libsci]
      fftw-api: [cray-fftw,fftw]
      pkgconfig: [pkg-config]

# don't build virtuals with a provider (probably tough)
  mpi:
    buildable: false
  blas:
    buildable: false
  lapack:
    buildable: false
  scalapack:
    buildable: false
  # ideally want to use cray optimised fftw but there are issues with cmake, mpi fftw and spack
  # hence set to true
  fftw-api:
    buildable: true
  pkgconfig:
    buildable: false
# don't build compilers neither
  gcc:
    buildable: false
  aocc:
    buildable: false
  intel:
    buildable: false
  pgi:
    buildable: false
  cce:
    buildable: false

  # packages found automatically by spack external find
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
    buildable: false
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
    buildable: false
  cmake:
    externals:
    - spec: cmake@3.10.2
      prefix: /usr
    buildable: true
  cpio:
    externals:
    - spec: cpio@2.12
      prefix: /usr
    buildable: false
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
    buildable: false
  file:
    externals:
    - spec: file@5.32
      prefix: /usr
    buildable: false
  findutils:
    externals:
    - spec: findutils@4.6.0
      prefix: /usr
    buildable: false
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
    buildable: false
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
    buildable: false
  gcc:
    externals:
    - spec: gcc@7.5.0 languages=c,c++,fortran
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc
          cxx: /usr/bin/g++
          fortran: /usr/bin/gfortran
    buildable: false
  git:
    externals:
    - spec: git@2.26.2~tcltk
      prefix: /usr
    buildable: false
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
    buildable: false
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
    buildable: false
  lustre:
    externals:
    - spec: lustre@2.12.4.2_cray_18_g0120bae
      prefix: /usr
    buildable: false
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
    buildable: false
  maven:
    externals:
    - spec: maven@3.6.0
      prefix: /usr/local/maven
    buildable: false
  openssh:
    externals:
    - spec: openssh@7.9p1
      prefix: /usr
    buildable: false
  openssl:
    externals:
    - spec: openssl@1.1.0i-fips
      prefix: /usr
    buildable: false
  perl:
    externals:
    - spec: perl@5.26.1~cpanm+shared+threads
      prefix: /usr
    buildable: true
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
    buildable: false
  python:
    externals:
    - spec: python@2.7.17+bz2+ctypes~dbm~lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
    - spec: python@3.6.12+bz2+ctypes~dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
    - spec: python@3.8.5+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true
  rsync:
    externals:
    - spec: rsync@3.1.3
      prefix: /usr
    buildable: false
  sed:
    externals:
    - spec: sed@4.4
      prefix: /usr
    buildable: false
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
    buildable: false
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /usr
    buildable: false
  xz:
    externals:
    - spec: xz@5.2.3
      prefix: /usr
    buildable: false

  # cray packages (manually added)
  # adding prefixes as in NERSC Perlmutter configs
  cray-mpich:
    externals:
    - spec: cray-mpich@7.7.0%gcc
      modules:
      - cray-mpich/8.1.7
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.7/ofi/gnu/9.1
    - spec: cray-mpich@7.7.0%cce
      modules:
      - cray-mpich/8.1.7
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.7/ofi/cray/10.0
    - spec: cray-mpich@7.7.0%aocc
      modules:
      - cray-mpich/8.1.7
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.7/ofi/aocc/3.0
    buildable: false
  cray-libsci:
    externals:
    - spec: cray-libsci@21.06.1.1%gcc
      modules:
      - cray-libsci/21.06.1.1
      prefix: /opt/cray/pe/libsci/21.06.1.1/gnu/9.1/x86_64
    - spec: cray-libsci@21.06.1.1%cce
      modules:
      - cray-libsci/21.06.1.1
      prefix: /opt/cray/pe/libsci/21.06.1.1/cray/9.0/x86_64
    - spec: cray-libsci@21.06.1.1%aocc
      modules:
      - cray-libsci/21.06.1.1
      prefix: /opt/cray/pe/libsci/21.06.1.1/aocc/2.0/x86_64
    buildable: false
  cray-fftw:
    externals:
    - spec: cray-fftw@3.3.8.10 target=zen2
      modules:
      - cray-fftw/3.3.8.10
      prefix: /opt/cray/pe/fftw/3.3.8.10/x86_rome
    - spec: cray-fftw@3.3.8.10 target=zen3
      modules:
      - cray-fftw/3.3.8.10
      prefix: /opt/cray/pe/fftw/3.3.8.10/x86_milan
    buildable: false
  # more cray
  jemalloc:
    externals:
    - spec: jemalloc@5.1.0.4
      modules:
      - cray-jemalloc/5.1.0.4
      prefix: /opt/cray/pe/jemalloc/5.1.0.4
    buildable: false
  libfabric:
    externals:
    - spec: libfabric@1.11.0.3.66
      modules:
      - libfabric/1.11.0.3.66
      prefix: /opt/cray/libfabric/1.11.0.3.66
    buildable: false
  ucx:
    externals:
    - spec: ucx@2.7.0-1
      modules:
      - cray-ucx/2.7.0-1
      prefix: /opt/cray/pe/cray-ucx/2.7.0-1/ucx
    buildable: false
  papi:
    externals:
    - spec: papi@6.0.0.7
      modules:
      - papi/6.0.0.7
      prefix: /opt/cray/pe/papi/6.0.0.7
    buildable: false
  r:
    externals:
    - spec: r@4.0.5.1
      prefix: /opt/cray/pe/R/4.0.5.1
    buildable: true
  # cray hdf5
  # cray netcdf
