packages:
  all:
    target: [cascadelake]
    compiler: [gcc@8.3.0, gcc@4.8.5]
    providers:
      mpi: [openmpi]
      blas: [intel-mkl]
      lapack: [intel-mkl]
      scalapack: [intel-mkl]
      fftw-api: [intel-mkl]
      mkl: [intel-mkl]
    permissions:
      read: world
      write: group
      group: pawsey0001
  mpi:
    buildable: false
  blas:
    buildable: false
  lapack:
    buildable: false
  scalapack:
    buildable: false
  fftw-api:
    buildable: false
  mkl:
    buildable: false
  gcc:
    buildable: false
  intel:
    buildable: false
  pgi:
    buildable: false
  intel-mkl:
    externals:
    - spec: intel-mkl@2019
      prefix: /pawsey/intel/19.0.5
    buildable: false
  cuda:
    externals:
    - spec: cuda@10.1.243
      prefix: /pawsey/centos7.6/devel/binary/cuda/10.1
    buildable: false
  gdrcopy:
    externals:
    - spec: gdrcopy@1.3
      prefix: /pawsey/centos7.6/devel/binary/cuda/10.1/gdrcopy-gpu/1.3
    buildable: false
  ucx:
    externals:
    - spec: ucx@1.6+cuda+gdrcopy+thread_multiple~optimizations cuda_arch=60 ^gdrcopy@1.3 ^cuda@10.1.243
      prefix: /pawsey/centos7.6/devel/gcc/4.8.5/cuda/10.1/ucx-gpu/1.6.0
    buildable: false
  openmpi:
    externals:
    - spec: openmpi@4.0.2%gcc@8.3.0+cuda~cxx~cxx_exceptions~java~memchecker+pmi~sqlite3~static~thread_multiple~wrapper-rpath
        fabrics=ofi,psm2,ucx,verbs schedulers=slurm ^ucx@1.6 ^cuda@10.1.243
      prefix: /pawsey/centos7.6/devel/broadwell/gcc/8.3.0/cuda/10.1/openmpi-ucx-gpu/4.0.2
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.13.4
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.18.0
      module: 
        - cmake/3.18.0
  cpio:
    externals:
    - spec: cpio@2.11
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.3
      prefix: /usr
  file:
    externals:
    - spec: file@5.11
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.5.11
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.5.37+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.0.2
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@9.07
      prefix: /usr
  git:
    externals:
    - spec: git@2.12.3
      module:
        - git/2.12.3
  gmake:
    externals:
    - spec: gmake@3.82
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.2
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.15.1
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.10.8
      prefix: /usr
  luster:
    externals:
    - spec: luster@2.10.8
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.16
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@5.9.2013051+termlib abi=5
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@7.4p1
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.0.2k-fips
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.16.3~cpanm+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.27.1
      prefix: /usr
  python:
    externals:
    - spec: python@3.6.3+bz2+ctypes+dbm+lzma+nis+pyexpat~readline~sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /pawsey/centos7.6/apps/gcc/4.8.5/python/3.6.3
    - spec: python@2.7.5+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@3.1.2
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@2.0.0
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.2.2
      prefix: /usr
  sqlite:
    externals:
    - spec: sqlite@3.7.17~fts~functions+rtree
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.26
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@5.1
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.2.2
      prefix: /usr
