upstreams:
# this is the location of the system wide installation
# it acts as an upstream installation for user-specific installations
  system_wide:
    install_tree: /software/joey/DATE_TAG/software
    modules:
      lmod: /software/joey/DATE_TAG/modules
