compilers:
# compilers automatically found by spack compiler find 
# on cray list a lot of unused and not useful 
# compilers hence we do not here 
# list all that are found. 

- compiler:
    spec: gcc@7.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

# updated to list explicit paths 
# and also have mpi module explicitly loaded as well  

# cray compilers 
- compiler:
    spec: cce@12.0.1
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-cray
    - cce/12.0.1
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

# gnu compilers 
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/10.3.0
    - craype-network-ofi
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.3.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/9.3.0
    - craype-network-ofi
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@8.1.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/8.1.0
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

# amd compilers 
- compiler:
    spec: aocc@3.0.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-aocc
    - aocc/3.0.0
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

