packages:
  all:
  # note the compiler and providers specifications
  # only suggest a priority order, they do not exclude other options
  # suggested priority for compilers.
    compiler: [gcc@10.3.0,cce,aocc]
    providers:
      mpi: [cray-mpich]
      blas: [cray-libsci]
      lapack: [cray-libsci]
      scalapack: [cray-libsci]
      fftw-api: [cray-fftw,fftw]
      pkgconfig: [pkg-config]
    permissions:
      read: world
      write: group
      group: pawsey0001
  cmake:
    version: [3.21.3]

# don't build virtuals with a provider (probably tough)
  mpi:
    buildable: false
  blas:
    buildable: false
  lapack:
    buildable: false
  scalapack:
    buildable: false
  # ideally want to use cray optimised fftw but there might be issues
  # remember, need to spack install fftw@2.1.5
  fftw-api:
    buildable: false
  pkgconfig:
    buildable: false
# don't build compilers neither
  gcc:
    buildable: false
  aocc:
    buildable: false
  intel:
    buildable: false
  pgi:
    buildable: false
  cce:
    buildable: false

# packages found automatically by spack external find
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
    buildable: false
#  bzip2:
#    externals:
#    - spec: bzip2@1.0.6
#      prefix: /usr
#    buildable: false
  cmake:
    externals:
  # manual addition with the latest version
    - spec: cmake@3.21.3
      prefix: /lus/joey/home/mdelapierre/spack/opt/spack/cray-sles15-zen2/gcc-10.3.0/cmake-3.21.3-ws6puo53ecnvukfyps2beb23dgv4imsg
    - spec: cmake@3.10.2
      prefix: /usr
  # in the future, maybe spack install a couple of recent versions, and make not buildable
    buildable: false
  cpio:
    externals:
    - spec: cpio@2.12
      prefix: /usr
    buildable: false
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
    buildable: false
  file:
    externals:
    - spec: file@5.32
      prefix: /usr
    buildable: false
  findutils:
    externals:
    - spec: findutils@4.6.0
      prefix: /usr
    buildable: false
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
    buildable: false
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
    buildable: false
  git:
    externals:
    - spec: git@2.26.2~tcltk
      prefix: /usr
    buildable: false
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
    buildable: false
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
    buildable: false
  lustre:
    externals:
    - spec: lustre@2.12.4.2_cray_18_g0120bae
      prefix: /usr
    buildable: false
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
    buildable: false
  maven:
    externals:
    - spec: maven@3.6.0
      prefix: /usr/local/maven
    buildable: false
  openssh:
    externals:
    - spec: openssh@7.9p1
      prefix: /usr
    buildable: false
  openssl:
    externals:
    - spec: openssl@1.1.0i-fips
      prefix: /usr
    buildable: false
  perl:
    externals:
    - spec: perl@5.26.1~cpanm
      prefix: /usr
    buildable: true
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
    buildable: false
  python:
    externals:
    - spec: python@2.7.17+bz2+ctypes~dbm~lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
    - spec: python@3.6.12+bz2+ctypes~dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
    - spec: python@3.8.5+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true
  rsync:
    externals:
    - spec: rsync@3.1.3
      prefix: /usr
    buildable: false
  sed:
    externals:
    - spec: sed@4.4
      prefix: /usr
    buildable: false
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
    buildable: false
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /usr
    buildable: false
  xz:
    externals:
    - spec: xz@5.2.3
      prefix: /usr
    buildable: false

# system packages (manually added)

# packages that are missing dev install with zypper 
# so commented out 
#  binutils:
#    externals:
#    - spec: binutils@2.35.1
#      prefix: /usr
#    buildable: false
#  hwloc:
#    externals:
#    - spec: hwloc@2.0.0
#      prefix: /usr
#    buildable: false
#  libxml2:
#    externals:
#    - spec: libxml2@2.9.7
#      prefix: /usr
#    buildable: false
#  libpciaccess:
#    externals:
#    - spec: libpciaccess@0.14
#      prefix: /usr
#    buildable: false
#  ncurses:
#    externals:
#    - spec: ncurses@6.1
#      prefix: /usr
#    - spec: ncurses@5.9
#      prefix: /usr
#    buildable: false

  curl:
    externals:
    - spec: curl@7.60.0
      prefix: /usr
    buildable: false
  fftw:
  # manual addition for fftw@2
    externals:
    - spec: fftw@2.1.5%gcc target=zen2
      prefix: /lus/joey/home/mdelapierre/spack/opt/spack/cray-sles15-zen2/gcc-10.3.0/fftw-2.1.5-qsx3jouinnj3e7e7hfy3uendvzn3x5mx
    - spec: fftw@2.1.5%cce target=zen2
      prefix: /lus/joey/home/mdelapierre/spack/opt/spack/cray-sles15-zen2/cce-12.0.1/fftw-2.1.5-3jxqf443ihzeu5ftm23kkxd7vdj4nhbv
    - spec: fftw@2.1.5%aocc target=zen2
      prefix: /lus/joey/home/mdelapierre/spack/opt/spack/cray-sles15-zen2/aocc-3.0.0/fftw-2.1.5-bh4tcpc5blq6rdflw7rinkmtie5qqjmn
    buildable: false
  libfuse:
    externals:
    - spec: libfuse@2.9.7
      prefix: /usr
  # current system installation misses binaries (and headers), hence buildable for now
    buildable: false
  lz4:
    externals:
    - spec: lz4@1.8.0
      prefix: /usr
    buildable: false
  numactl:
    externals:
    - spec: numactl@2.0.11
      prefix: /usr
    buildable: false
  slurm:
    externals:
    - spec: slurm@20-11-5-1
      prefix: /usr
    buildable: false
  wget:
    externals:
    - spec: wget@1.20.3
      prefix: /usr
    buildable: false
  zlib:
    externals:
    - spec: zlib@1.2.11
      prefix: /usr
    buildable: false
  zstd:
    externals:
    - spec: zstd@1.4.4
      prefix: /usr
    buildable: false

# cray packages (manually added)
# adding prefixes as in NERSC Perlmutter configs
  cray-mpich:
    externals:
    - spec: cray-mpich@7.7.0%gcc
      modules:
      - cray-mpich/8.1.7
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.7/ofi/gnu/9.1
    - spec: cray-mpich@7.7.0%cce
      modules:
      - cray-mpich/8.1.7
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.7/ofi/cray/10.0
    - spec: cray-mpich@7.7.0%aocc
      modules:
      - cray-mpich/8.1.7
      - craype-network-ofi
      prefix: /opt/cray/pe/mpich/8.1.7/ofi/aocc/3.0
    buildable: false
  cray-libsci:
    externals:
    - spec: cray-libsci@21.06.1.1%gcc
      modules:
      - cray-libsci/21.06.1.1
      prefix: /opt/cray/pe/libsci/21.06.1.1/gnu/9.1/x86_64
    - spec: cray-libsci@21.06.1.1%cce
      modules:
      - cray-libsci/21.06.1.1
      prefix: /opt/cray/pe/libsci/21.06.1.1/cray/9.0/x86_64
    - spec: cray-libsci@21.06.1.1%aocc
      modules:
      - cray-libsci/21.06.1.1
      prefix: /opt/cray/pe/libsci/21.06.1.1/aocc/2.0/x86_64
    buildable: false
  cray-fftw:
    externals:
    - spec: cray-fftw@3.3.8.10 target=zen2
      modules:
      - cray-fftw/3.3.8.10
      prefix: /opt/cray/pe/fftw/3.3.8.10/x86_rome
    - spec: cray-fftw@3.3.8.10 target=zen3
      modules:
      - cray-fftw/3.3.8.10
      prefix: /opt/cray/pe/fftw/3.3.8.10/x86_milan
    buildable: false
  # more cray
  jemalloc:
    externals:
    - spec: jemalloc@5.1.0.4
      modules:
      - cray-jemalloc/5.1.0.4
      prefix: /opt/cray/pe/jemalloc/5.1.0.4
    buildable: false
  xpmem:
    externals:
    - spec: xpmem@2.2.40
      modules:
      - xpmem/2.2.40-7.0.1.0_1.9__g1d7a24d.shasta
      prefix: /opt/cray/xpmem/2.2.40-7.0.1.0_1.9__g1d7a24d.shasta
    buildable: false
  libfabric:
    externals:
    - spec: libfabric@1.11.0.3.66
      modules:
      - libfabric/1.11.0.3.66
      prefix: /opt/cray/libfabric/1.11.0.3.66
    buildable: false
  ucx:
    externals:
    - spec: ucx@2.7.0-1
      modules:
      - cray-ucx/2.7.0-1
      prefix: /opt/cray/pe/cray-ucx/2.7.0-1/ucx
    buildable: false
  papi:
    externals:
    - spec: papi@6.0.0.7
      modules:
      - papi/6.0.0.7
      prefix: /opt/cray/pe/papi/6.0.0.7
    buildable: false
  r:
    externals:
    - spec: r@4.0.5.1
      prefix: /opt/cray/pe/R/4.0.5.1
    buildable: true

# cray hdf5
  hdf5:
    externals:
    - spec: hdf5@1.12.0.5%gcc~tools~mpi
      modules:
      - cray-hdf5/1.12.0.5
      prefix: /opt/cray/pe/hdf5/1.12.0.5/gnu/9.1
    - spec: hdf5@1.12.0.5%gcc~tools+mpi~cxx
      modules:
      - cray-hdf5-parallel/1.12.0.5
      prefix: /opt/cray/pe/hdf5-parallel/1.12.0.5/gnu/9.1
    - spec: hdf5@1.12.0.5%cce~tools~mpi
      modules:
      - cray-hdf5/1.12.0.5
      prefix: /opt/cray/pe/hdf5/1.12.0.5/crayclang/10.0
    - spec: hdf5@1.12.0.5%cce~tools+mpi~cxx
      modules:
      - cray-hdf5-parallel/1.12.0.5
      prefix: /opt/cray/pe/hdf5-parallel/1.12.0.5/crayclang/10.0
    - spec: hdf5@1.12.0.5%aocc~tools~mpi
      modules:
      - cray-hdf5/1.12.0.5
      prefix: /opt/cray/pe/hdf5/1.12.0.5/aocc/2.2
    - spec: hdf5@1.12.0.5%aocc~tools+mpi~cxx
      modules:
      - cray-hdf5-parallel/1.12.0.5
      prefix: /opt/cray/pe/hdf5-parallel/1.12.0.5/aocc/2.2
    buildable: false

# cray parallel-netcdf
  parallel-netcdf:
    externals:
    - spec: parallel-netcdf@1.12.1.5%gcc
      modules:
      - cray-parallel-netcdf/1.12.1.5
      prefix: /opt/cray/pe/parallel-netcdf/1.12.1.5/gnu/9.1
    - spec: parallel-netcdf@1.12.1.5%cce
      modules:
      - cray-parallel-netcdf/1.12.1.5
      prefix: /opt/cray/pe/parallel-netcdf/1.12.1.5/crayclang/10.0
    - spec: parallel-netcdf@1.12.1.5%aocc
      modules:
      - cray-parallel-netcdf/1.12.1.5
      prefix: /opt/cray/pe/parallel-netcdf/1.12.1.5/aocc/2.2
    buildable: false

# cray netcdf
  netcdf-c:
    externals:
    - spec: netcdf-c@4.7.4.5%gcc~mpi
      modules:
      - cray-hdf5/1.12.0.5
      - cray-netcdf/4.7.4.5
      prefix: /opt/cray/pe/netcdf/4.7.4.5/gnu/9.1
    - spec: netcdf-c@4.7.4.5%gcc+mpi
      modules:
      - cray-hdf5-parallel/1.12.0.5
      - cray-netcdf-hdf5parallel/4.7.4.5
      prefix: /opt/cray/pe/netcdf-hdf5parallel/4.7.4.5/gnu/9.1
    - spec: netcdf-c@4.7.4.5%cce~mpi
      modules:
      - cray-hdf5/1.12.0.5
      - cray-netcdf/4.7.4.5
      prefix: /opt/cray/pe/netcdf/4.7.4.5/crayclang/10.0
    - spec: netcdf-c@4.7.4.5%cce+mpi
      modules:
      - cray-hdf5-parallel/1.12.0.5
      - cray-netcdf-hdf5parallel/4.7.4.5
      prefix: /opt/cray/pe/netcdf-hdf5parallel/4.7.4.5/crayclang/10.0
    - spec: netcdf-c@4.7.4.5%aocc~mpi
      modules:
      - cray-hdf5/1.12.0.5
      - cray-netcdf/4.7.4.5
      prefix: /opt/cray/pe/netcdf/4.7.4.5/aocc/2.2
    - spec: netcdf-c@4.7.4.5%aocc+mpi
      modules:
      - cray-hdf5-parallel/1.12.0.5
      - cray-netcdf-hdf5parallel/4.7.4.5
      prefix: /opt/cray/pe/netcdf-hdf5parallel/4.7.4.5/aocc/2.2
    buildable: false
  netcdf-fortran:
    externals:
    - spec: netcdf-fortran@4.7.4.5%gcc
      modules:
      - cray-hdf5/1.12.0.5
      - cray-netcdf/4.7.4.5
      prefix: /opt/cray/pe/netcdf/4.7.4.5/gnu/9.1
    - spec: netcdf-fortran@4.7.4.5%cce
      modules:
      - cray-hdf5/1.12.0.5
      - cray-netcdf/4.7.4.5
      prefix: /opt/cray/pe/netcdf/4.7.4.5/crayclang/10.0
    - spec: netcdf-fortran@4.7.4.5%aocc
      modules:
      - cray-hdf5/1.12.0.5
      - cray-netcdf/4.7.4.5
      prefix: /opt/cray/pe/netcdf/4.7.4.5/aocc/2.2
    buildable: false
  netcdf-cxx4:
    externals:
    - spec: netcdf-cxx4@4.7.4.5%gcc
      modules:
      - cray-hdf5/1.12.0.5
      - cray-netcdf/4.7.4.5
      prefix: /opt/cray/pe/netcdf/4.7.4.5/gnu/9.1
    - spec: netcdf-cxx4@4.7.4.5%cce
      modules:
      - cray-hdf5/1.12.0.5
      - cray-netcdf/4.7.4.5
      prefix: /opt/cray/pe/netcdf/4.7.4.5/crayclang/10.0
    - spec: netcdf-cxx4@4.7.4.5%aocc
      modules:
      - cray-hdf5/1.12.0.5
      - cray-netcdf/4.7.4.5
      prefix: /opt/cray/pe/netcdf/4.7.4.5/aocc/2.2
    buildable: false


# python additions 
# based on loading cray-python and 
# running pip list 
# standard python packages 
  py-atomicwrites:
    externals:
    - spec: py-atomicwrites@1.3.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false 
  py-attrs:
    externals:
    - spec: py-attrs@19.3.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false 
  py-cython:
    externals:
    - spec: py-cython@0.29.15
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true 
  # not certain about dask-mpi in spack and 
  # whether cray provides it. Normally it 
  # would be listed separately 
  py-fsspec:
    externals:
    - spec: py-fsspec@0.7.4
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false 
  py-importlib-metadata:
    externals:
    - spec: py-importlib-metadata@1.5.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-locket:
    externals:
    - spec: py-locket@0.2.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-more-itertools:
    externals:
    - spec: py-more-itertools@8.2.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-nose:
    externals:
    - spec: py-nose@1.3.7
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-packaging:
    externals:
    - spec: py-packaging@1.18.2
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-partd:
    externals:
    - spec: py-partd@1.1.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-pip:
    externals:
    - spec: py-pip@20.1.1
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-pluggy:
    externals:
    - spec: py-pluggy@0.13.1
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-py:
    externals:
    - spec: py-py@1.8.1
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-pyparsing:
    externals:
    - spec: py-pyparsing@2.4.6
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  # this is an old verison of pytest so buildable
  py-pytest:
    externals:
    - spec: py-pytest@5.3.5
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true
  py-python-dateutil:
    externals:
    - spec: py-python-dateutil@2.8.1
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-pytz:
    externals:
    - spec: py-pytz@2020.1
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  # this is an old verison so buildable
  py-setuptools:
    externals:
    - spec: py-setuptools@47.1.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true
  # this is an old verison so buildable
  py-setuptools-scm:
    externals:
    - spec: py-setuptools-scm@3.4.3
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true
  py-six:
    externals:
    - spec: py-six@1.14.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-toolz:
    externals:
    - spec: py-toolz@0.10.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-wcwidth:
    externals:
    - spec: py-wcwidth@0.1.8
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  # this is an old verison so buildable
  py-zipp:
    externals:
    - spec: py-zipp@2.2.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true

# python packages that might want to rebuild 
  py-dask:
    externals:
    - spec: py-dask@2.13.0
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true 
  # wonder if this should be buildable
  py-mpi4py:
    externals:
    - spec: py-mpi4py@3.0.3
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: false
  py-numpy:
    externals:
    - spec: py-numpy@1.18.2
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true 
  py-pandas:
    externals:
    - spec: py-pandas@1.0.5
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true
  py-scipy:
    externals:
    - spec: py-scipy@1.4.1
      modules:
      - cray-python
      prefix: /opt/cray/pe/python/3.8.5.1
    buildable: true
