packages:
  # set packages for all builds
  # first is to use mpich for all mpi
  # and cray-libsci for all blas, lapack and scalapack
  all:
    providers:
      mpi: [mpich]
      blas: [cray-libsci]
      lapack: [cray-libsci]
      scalapack: [cray-libsci]
      fftw-api: [fftw]
      pkgconfig: [pkg-config]
# MARCO: don't build virtuals with a provider (probably tough)
  mpi:
    buildable: false
  blas:
    buildable: false
  lapack:
    buildable: false
  scalapack:
    buildable: false
# allow for fftw additional builds, Cray has issues
  fftw-api:
    buildable: true
  pkgconfig:
    buildable: false
# MARCO: don't build compilers neither
  gcc:
    buildable: false
  intel:
    buildable: false
  pgi:
    buildable: false
  cce:
    buildable: false

  # packages found automatically by spack 
  # with spack external find
  # by default buildable: false has been added to these entries 
  # that are /usr prefix installs 
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
    buildable: false 
  automake:
    externals:
    - spec: automake@1.13.4
      prefix: /usr
    buildable: false 
  bash:
    externals:
    - spec: bash@4.3.48
      prefix: /
    buildable: false 
  bison:
    externals:
    - spec: bison@2.7
      prefix: /usr
    buildable: false 
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
    buildable: false 
  cmake:
    externals:
    - spec: cmake@3.18.0
      prefix: /pawsey/cle60up07/devel/gcc/4.8.5/cmake/3.18.0
    - spec: cmake@3.5.2
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.11
      prefix: /usr
    buildable: false 
  diffutils:
    externals:
    - spec: diffutils@3.3
      prefix: /usr
    buildable: false 
  doxygen:
    externals:
    - spec: doxygen@1.8.6+graphviz~mscgen
      prefix: /usr
    buildable: false 
  findutils:
    externals:
    - spec: findutils@4.5.12
      prefix: /usr
    buildable: false 
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
    buildable: false 
  gawk:
    externals:
    - spec: gawk@4.1.0
      prefix: /usr
    buildable: false 
  # This is found by spack but is a compiler 
  # Thus external find command will 
  # need edits afterwards
  # gcc:
  #  externals:
  #  - spec: gcc@4.8 languages=c,c++
  #    prefix: /usr
  #    extra_attributes:
  #      compilers:
  #        c: /usr/bin/gcc
  #        cxx: /usr/bin/g++-4.8
  #  - spec: gcc@7.2.0 languages=c,c++,fortran
  #    prefix: /opt/gcc/7.2.0
  #    extra_attributes:
  #      compilers:
  #        c: /opt/gcc/7.2.0/bin/gcc
  #        cxx: /opt/gcc/7.2.0/bin/g++
  #        fortran: /opt/gcc/7.2.0/bin/gfortran
  ghostscript:
    externals:
    - spec: ghostscript@9.52
      prefix: /usr
    buildable: false 
  git:
    externals:
    - spec: git@2.26.2~tcltk
      prefix: /usr
    buildable: false 
  gmake:
    externals:
    - spec: gmake@4.0
      prefix: /usr
    buildable: false 
  groff:
    externals:
    - spec: groff@1.22.2
      prefix: /usr
    buildable: false 
  krb5:
    externals:
    - spec: krb5@1.12.5
      prefix: /usr/lib/mit
    buildable: false 
  libfuse:
    externals:
    - spec: libfuse@2.9.3
      prefix: /usr
    buildable: false 
  libtool:
    externals:
    - spec: libtool@2.4.2
      prefix: /usr
    buildable: false 
  lustre:
    externals:
    - spec: lustre@2.7.5.13
      prefix: /
    buildable: false 
  m4:
    externals:
    - spec: m4@1.4.16
      prefix: /usr
    buildable: false 
  ncurses:
    externals:
    - spec: ncurses@5.9.20140201+termlib abi=5
      prefix: /usr
    - spec: ncurses@5.9.20140201+termlib abi=6
      prefix: /usr
    buildable: false 
  openssh:
    externals:
    - spec: openssh@7.2p2
      prefix: /usr
    buildable: false 
  openssl:
    externals:
    - spec: openssl@1.0.2j-fips
      prefix: /usr
    buildable: false 
  perl:
    externals:
    - spec: perl@5.18.2~cpanm+shared+threads
      prefix: /usr
    # for interpreter langauges allow for spack build specific versions 
    buildable: true
  pkg-config:
    externals:
    - spec: pkg-config@0.28
      prefix: /usr
    buildable: false 
  rsync:
    externals:
    - spec: rsync@3.1.0
      prefix: /usr
    buildable: false 
  ruby:
    externals:
    - spec: ruby@2.1.9
      prefix: /usr
    # for interpreter langauges allow for spack build specific versions 
    buildable: true
  tar:
    externals:
    - spec: tar@1.27.1
      prefix: /usr
    buildable: false 
  texinfo:
    externals:
    - spec: texinfo@4.13
      prefix: /usr
    buildable: false 
  texlive:
    externals:
    - spec: texlive@20130530
      prefix: /usr
    buildable: false 
  xz:
    externals:
    - spec: xz@5.0.5
      prefix: /usr
    buildable: false 

  # manully added packages present on the system 
  # that were not found by spack external find
  libx11:
    externals:
    - spec: libx11@1.7.0
      prefix: /usr/
    buildable: false
  readline:
    externals:
    - spec: readline@8.0
      prefix: /usr/
    buildable: false
  libxml2:
    externals:
    - spec: libxml2@2.9.4-46.37.1
      prefix: /usr
    buildable: false
  hwloc:
    externals:
    - spec: hwloc@1.11.8-6.0.7.1_5.2__g21957d59
      prefix: /usr
    buildable: false

  # python found in /usr path. This may require updates if optimised python packages 
  # present in different directory structure. 
  # first python is the python loaded by module load python/3.6.3 but has 
  # been found and set with the prefix. 
  python:
    externals:
    - spec: python@3.6.3+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
      prefix: /pawsey/cle60up07/apps/gcc/4.8.5/python/3.6.3
    - spec: python@2.7.17+bz2+ctypes~dbm~lzma+nis+pyexpat+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
      prefix: /usr
    - spec: python@3.4.10+bz2+ctypes~dbm+lzma+nis~pyexpat~readline~sqlite3~ssl~tix~tkinter+uuid+zlib
      prefix: /usr
    # allow for spack built specific versions 
    buildable: true 

  # packages present in the modules 
  # added manually 
  
  # for cray libraries, have been careful to list the compiler family 
  # that libraries exist for. 
  mpich:
    externals:
    - spec: mpich@7.7.0%cce
      modules:
      - cray-mpich/7.7.0
    - spec: mpich@7.7.0%gcc
      modules:
      - cray-mpich/7.7.0
    - spec: mpich@7.7.0%intel
      modules:
      - cray-mpich/7.7.0
    # force spack to use this mpi but setting this to false
    buildable: false
  # use the cray provided blas and lapack 
  # really should do this for all cray provided packages
  cray-libsci:
    externals:
    - spec: cray-libsci@19.06.1%cce
      modules:
      - cray-libsci/19.06.1
    - spec: cray-libsci@19.06.1%gcc
      modules:
      - cray-libsci/19.06.1
    - spec: cray-libsci@19.06.1%intel
      modules:
      - cray-libsci/19.06.1
    # force spack to use this mpi but setting this to false
    buildable: false
  fftw:
    externals:
    - spec: fftw@3.3.6.3+mpi~openmp~pfft_patches precision=double,float%cce
      modules:
      - cray-fftw/3.3.6.3
    - spec: fftw@3.3.6.3+mpi~openmp~pfft_patches precision=double,float%gcc
      modules:
      - cray-fftw/3.3.6.3
    - spec: fftw@3.3.6.3+mpi~openmp~pfft_patches precision=double,float%intel
      modules:
      - cray-fftw/3.3.6.3
    # ideally want to use cray optimised fftw but there are issues with cmake, mpi fftw and spack
    # hence set to true
    buildable: true

  # there may be a need to build hdf5 variants with spack since 
  # cray does not provide all possible api's. 
  # should update to list compiler families that these are viable for 
  hdf5:
    externals:
    - spec: hdf5@1.10.1+cxx+fortran+hl~java~mpi+shared+szip+threadsafe api=v110 build_type=Release
      modules:
      - cray-hdf5/1.10.1
    - spec: hdf5@1.10.5+cxx+fortran+hl~java~mpi+shared+szip+threadsafe api=v110 build_type=Release
      modules:
      - cray-hdf5/1.10.5
    - spec: hdf5@1.10.1~cxx+fortran+hl~java+mpi+shared+szip+threadsafe api=v110 build_type=Release
      modules:
      - cray-hdf5-parallel/1.10.1
    - spec: hdf5@1.10.5~cxx+fortran+hl~java+mpi+shared+szip+threadsafe api=v110 build_type=Release
      modules:
      - cray-hdf5-parallel/1.10.5
    buildable: true

  # slurm module 
  slurm:
    externals:
    - spec: slurm@20.02.5-1
      modules:
      - slurm/20.02.5-1
    buildable: false

  # netcdf packages are all set to buildable = true
  # as there appears to be some compatibility issues 
  # with spack built packages. 
  # Further testing could resolve this issue and it
  # may be possible to set these to buildable = false
  parallel-netcdf:
    externals:
    - spec: parallel-netcdf@1.12.0.0+fortran+cxx+pic+shared
      modules:
      - cray-parallel-netcdf/1.12.0.0
    - spec: parallel-netcdf@1.11.1.1+fortran+cxx+pic+shared
      modules:
      - cray-parallel-netcdf/1.11.1.1
    - spec: parallel-netcdf@1.8.1.3+fortran+cxx+pic+shared
      modules:
      - cray-parallel-netcdf/1.8.1.3
    buildable: true
  netcdf-c:
    externals:
    - spec: netcdf-c@4.6.3.2~dap~hdf4~jna+mpi~parallel-netcdf+pic+shared
      modules:
      - cray-netcdf/4.6.3.2
    - spec: netcdf-c@4.4.1.1.6~dap~hdf4~jna+mpi~parallel-netcdf+pic+shared
      modules:
      - cray-netcdf/4.4.1.1.6
    buildable: true
  netcdf-fortran:
    externals:
    - spec: netcdf-fortran@4.6.3.2~doc+pic+shared
      modules:
      - cray-netcdf/4.6.3.2
    - spec: netcdf-fortran@4.4.1.1.6~doc+pic+shared
      modules:
      - cray-netcdf/4.4.1.1.6
    buildable: true
  netcdf-cxx:
    externals:
    - spec: netcdf-cxx@4.6.3.2+netcdf4
      modules:
      - cray-netcdf/4.6.3.2
    - spec: netcdf-cxx@4.4.1.1.6+netcdf4
      modules:
      - cray-netcdf/4.4.1.1.6
    buildable: true

  # other modules avail
  cmake:
    externals:
    - spec: cmake@3.18.0~doc+ncurses+openssl+ownlibs~qt build_type=Release
      modules:
      - cmake@3.18.0
    buildable: false
  yasm:
    externals:
    - spec: yasm@1.3.0
      modules:
      - yasm@1.3.0
    buildable: false
  ffmpeg:
    externals:
    - spec: ffmpeg@3.4.0
      modules:
      - ffmpeg@3.4
    buildable: false
