compilers:
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: sles12
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@4.8
- compiler:
    paths:
      cc: /pawsey/sles12sp3/devel/gcc/4.8.5/gcc/8.3.0/bin/gcc
      cxx: /pawsey/sles12sp3/devel/gcc/4.8.5/gcc/8.3.0/bin/g++
      f77: /pawsey/sles12sp3/devel/gcc/4.8.5/gcc/8.3.0/bin/gfortran
      fc: /pawsey/sles12sp3/devel/gcc/4.8.5/gcc/8.3.0/bin/gfortran
    operating_system: sles12
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@8.3.0
