config:
  build_stage: $spack/var/spack/stage

  # Directory in which to run tests and store test results.
  # Tests will be stored in directories named by date/time and package
  # name/hash.
  test_stage: $spack/var/spack/test

  # Cache directory for already downloaded source tarballs and archived
  # repositories. This can be purged with `spack clean --downloads`.
  source_cache: $spack/var/spack/cache

  # Cache directory for miscellaneous files, like the package index.
  # This can be purged with `spack clean --misc-cache`
  misc_cache: $spack/var/spack/misc-cache

  install_tree:
    # due to file lock issues, do not install in the standard path
    # listed below
    # root: /pawsey/sles12sp3/spack/software/
    # software is installed here but will require use of chrpath to work
    # once manually moved to above path
    root: /group/pawsey0001/maali/software/sles12sp3/spack/software/

  template_dirs:
    - /group/pawsey0001/maali/pawsey-spack-config/examples/zeus/templates

  concretizer: original