packages:
  all:
    target: [broadwell]
    compiler: [gcc@8.3.0, gcc@4.8.5]
    providers:
      mpi: [openmpi]
      blas: [intel-mkl]
      lapack: [intel-mkl]
      scalapack: [intel-mkl]
      fftw-api: [intel-mkl, fftw]
      mkl: [intel-mkl]
  openmpi:
    externals:
    - spec: openmpi@2.1.2%gcc@8.3.0~cuda~cxx~cxx_exceptions~java~memchecker+pmi~sqlite3~static~thread_multiple~wrapper-rpath
        fabrics=psm2 schedulers=loadleveler,slurm
      prefix: /pawsey/sles12sp3/devel/sandybridge/gcc/8.3.0/openmpi/2.1.2
  intel-mkl:
    externals:
    - spec: intel-mkl@2017
      prefix: /pawsey/intel/17.0.5
    buildable: false
  mpi:
    buildable: false
  gcc:
    buildable: false
  intel:
    buildable: false
  pgi:
    buildable: false
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.13.4
      prefix: /usr
  bison:
    externals:
    - spec: bison@2.7
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.5.2
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.11
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.3
      prefix: /usr
  file:
    externals:
    - spec: file@5.22
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.5.12
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.5.37+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.1.0
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@9.26
      prefix: /usr
  git:
    externals:
    - spec: git@2.12.3+tcltk
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.0
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.2
      prefix: /usr
  libfuse:
    externals:
    - spec: libfuse@2.9.3
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.2
      prefix: /usr
  lustre:
    externals:
    - spec: lustre@2.10.8
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.16
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@5.9.20140201+termlib abi=5
      prefix: /usr
    - spec: ncurses@5.9.20140201+termlib abi=6
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@7.2p2
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.0.2j-fips
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.18.2~cpanm+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.28
      prefix: /usr
  python:
    externals:
    - spec: python@3.6.3+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
      prefix: /pawsey/sles12sp3/apps/gcc/4.8.5/python/3.6.3
    - spec: python@2.7.13+bz2+ctypes~dbm~lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@3.1.0
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@2.1.9
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.2.2
      prefix: /usr
  sqlite:
    externals:
    - spec: sqlite@3.8.10.2~fts~functions+rtree
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@4.13
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.0.5
      prefix: /usr

