repos:
# this list is interpreted as a priority list, 
# in that items higher up in the list are inspected first
# and take precedence
# 
# Spack user (Pawsey staff) populates this one with fixed recipes for Setonix
# that are not (yet) in the Spack public repo
- /askapingest/pawsey0001/maali/pawsey-spack-config/setonix/repo_setonix
