packages:
  all:
    target: [zen2]
    compiler: [gcc@8.3.0, gcc@9.2.0, gcc@4.8.5]
    providers:
      mpi: [openmpi]
      blas: [openblas]
      lapack: [openblas]
      scalapack: [openblas]
    permissions:
      read: world
      write: group
      group: pawsey0001
  mpi:
    buildable: false
  blas:
    buildable: false
  lapack:
    buildable: false
  scalapack:
    buildable: false
  fftw-api:
    buildable: false
  mkl:
    buildable: false
  gcc:
    buildable: false
  intel:
    buildable: false
  pgi:
    buildable: false

  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.13.4
      prefix: /usr
  bison:
    externals:
    - spec: bison@2.7
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.5.2
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.11
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.3
      prefix: /usr
  file:
    externals:
    - spec: file@5.22
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.5.12
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.1.0
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@9.52
      prefix: /usr
  git:
    externals:
    - spec: git@2.26.2+tcltk
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.0
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.2
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.12.5
      prefix: /usr/lib/mit
  libfuse:
    externals:
    - spec: libfuse@2.9.3
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.2
      prefix: /usr
  lustre:
    externals:
    - spec: lustre@2.12.5
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.16
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@5.9.20140201+termlib abi=5
      prefix: /usr
    - spec: ncurses@5.9.20140201+termlib abi=6
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@7.2p2
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.0.2p-fips
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.18.2~cpanm+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.28
      prefix: /usr
  python:
    externals:
    - spec: python@3.9.7+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
      prefix: /pawsey/askapingest_sles12sp5/apps/gcc/4.8.5/python/3.9.7
    - spec: python@2.7.17+bz2+ctypes~dbm~lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@3.1.3
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@2.1.9
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.2.2
      prefix: /usr
  sqlite:
    externals:
    - spec: sqlite@3.36.0+fts~functions+rtree
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@4.13
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.0.5
      prefix: /usr
  ucx:
    externals:
    - spec: ucx@1.6~cuda~gdrcopy+thread_multiple~optimizations
      prefix: /pawsey/askapingest_sles12sp5/devel/gcc/4.8.5/ucx/1.6.0/
    buildable: false
  openmpi:
    externals:
    - spec: openmpi@4.0.3%gcc@8.3.0~cuda~cxx~cxx_exceptions~java~memchecker+pmi~sqlite3~static~thread_multiple~wrapper-rpath
        fabrics=ofi,psm2,ucx,verbs schedulers=slurm ^ucx@1.6 ^cuda@10.1.243
      prefix: /pawsey/askapingest_sles12sp5/devel/epyc/gcc/8.3.0/openmpi-ucx/4.0.3/
    buildable: false
  openblas:
    externals:
    - spec: openblas@0.3.13 
      modules:
        - openblas/0.3.13
    buildable: false
